import os

# Minimal valid env for tests that import modules requiring Settings at import time.
os.environ.setdefault("APP_ENV", "dev")
os.environ.setdefault("APP_NAME", "grantpilot")
os.environ.setdefault("APP_BASE_URL", "http://localhost:8000")
os.environ.setdefault("CORS_ALLOWED_ORIGINS", "http://localhost:3000")
os.environ.setdefault("LOG_LEVEL", "INFO")
os.environ.setdefault("DATABASE_URL", "postgresql://localhost/grantpilot_test")
os.environ.setdefault("AUTH_JWT_SIGNING_KEY", "x" * 64)
os.environ.setdefault("AUTH_ACCESS_TOKEN_TTL_MIN", "15")
os.environ.setdefault("AUTH_REFRESH_TOKEN_TTL_DAYS", "30")
os.environ.setdefault("AUTH_MAGIC_LINK_TTL_MIN", "15")
os.environ.setdefault("AUTH_ALLOWED_REDIRECT_URLS", "http://localhost:3000/auth/callback")
os.environ.setdefault("AUTH_RATE_LIMIT_ENABLED", "false")
os.environ.setdefault("GOOGLE_OAUTH_CLIENT_ID", "client")
os.environ.setdefault("GOOGLE_OAUTH_CLIENT_SECRET", "secret")
os.environ.setdefault(
    "GOOGLE_OAUTH_REDIRECT_URI", "http://localhost:8000/auth/google/callback"
)
os.environ.setdefault("EMAIL_PROVIDER", "resend")
os.environ.setdefault("EMAIL_FROM_NAME", "NGOInfo")
os.environ.setdefault("EMAIL_FROM_ADDRESS", "support@ngoinfo.org")
os.environ.setdefault("EMAIL_API_KEY", "re_test")
os.environ.setdefault("OPENAI_API_KEY", "sk-test")
os.environ.setdefault("PROMPT_VERSION", "v1.0.0")
os.environ.setdefault("STRIPE_MODE", "test")
os.environ.setdefault("STRIPE_SECRET_KEY", "sk_test_fake")
os.environ.setdefault("STRIPE_WEBHOOK_SECRET", "whsec_fake")
os.environ.setdefault("STRIPE_CHECKOUT_SUCCESS_URL", "http://localhost:3000/billing/success")
os.environ.setdefault("STRIPE_CHECKOUT_CANCEL_URL", "http://localhost:3000/billing/cancel")
os.environ.setdefault("STRIPE_PRICE_ID_GROWTH", "price_growth")
os.environ.setdefault("STRIPE_PRICE_ID_IMPACT", "price_impact")
os.environ.setdefault("ME_MODULE_ENABLED", "false")
